plugins:
  custom_post_display_enabled:
    default: false
  custom_post_display_badge_ids:
    default: ''
  custom_post_display_join_format:
    default: '%-m/%y'
  custom_post_display_help_url:
    default: ''
    client: true
